// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLBH.Controllers.Data;

namespace QLBH.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230919104938_data")]
    partial class data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QLBH.Controllers.Data.Customer", b =>
                {
                    b.Property<Guid>("maKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dchi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hoten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Nsinh")
                        .HasColumnType("datetime2");

                    b.HasKey("maKH");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("QLBH.Controllers.Data.Employer", b =>
                {
                    b.Property<Guid>("maNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dchi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hoten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Nvaolam")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maNV");

                    b.ToTable("Employer");
                });

            modelBuilder.Entity("QLBH.Controllers.Data.Invoice", b =>
                {
                    b.Property<Guid>("maHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Nlap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<double>("Ttien")
                        .HasColumnType("float");

                    b.Property<Guid>("maKH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("maNV")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("maHD");

                    b.HasIndex("maKH");

                    b.HasIndex("maNV");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("QLBH.Controllers.Data.InvoiceDetails", b =>
                {
                    b.Property<Guid>("maHD")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("maSP")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sluong")
                        .HasColumnType("int");

                    b.HasKey("maHD", "maSP");

                    b.HasIndex("maSP");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("QLBH.Controllers.Data.Product", b =>
                {
                    b.Property<Guid>("maSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DVT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GiaSP")
                        .HasColumnType("float");

                    b.Property<int>("Lton")
                        .HasColumnType("int");

                    b.Property<string>("TenSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("giamgia")
                        .HasColumnType("float");

                    b.HasKey("maSP");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("QLBH.Controllers.Data.Invoice", b =>
                {
                    b.HasOne("QLBH.Controllers.Data.Customer", "customer")
                        .WithMany("invoices")
                        .HasForeignKey("maKH")
                        .HasConstraintName("FK_Inv_Cus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLBH.Controllers.Data.Employer", "employer")
                        .WithMany("invoices")
                        .HasForeignKey("maNV")
                        .HasConstraintName("FK_Inv_Emp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");

                    b.Navigation("employer");
                });

            modelBuilder.Entity("QLBH.Controllers.Data.InvoiceDetails", b =>
                {
                    b.HasOne("QLBH.Controllers.Data.Invoice", "invoice")
                        .WithMany("invoiceDetails")
                        .HasForeignKey("maHD")
                        .HasConstraintName("FK_IDetails_Inv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLBH.Controllers.Data.Product", "product")
                        .WithMany("invoiceDetails")
                        .HasForeignKey("maSP")
                        .HasConstraintName("FK_IDetails_Product")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("invoice");

                    b.Navigation("product");
                });

            modelBuilder.Entity("QLBH.Controllers.Data.Customer", b =>
                {
                    b.Navigation("invoices");
                });

            modelBuilder.Entity("QLBH.Controllers.Data.Employer", b =>
                {
                    b.Navigation("invoices");
                });

            modelBuilder.Entity("QLBH.Controllers.Data.Invoice", b =>
                {
                    b.Navigation("invoiceDetails");
                });

            modelBuilder.Entity("QLBH.Controllers.Data.Product", b =>
                {
                    b.Navigation("invoiceDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
